import {MigrationInterface, QueryRunner} from "typeorm";

export class NewMigration1544084986883 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "current_ranks" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "profileId" varchar NOT NULL, "region" varchar NOT NULL, "season" integer NOT NULL, "skillMean" integer NOT NULL, "skillStdev" integer NOT NULL, "wins" integer NOT NULL, "losses" integer NOT NULL, "abandons" integer NOT NULL, "mmr" integer NOT NULL, "maxMmr" integer NOT NULL, "rank" integer NOT NULL, "maxRank" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "handled" boolean NOT NULL, CONSTRAINT "current_ranks_profile_id_region_season_unique_idx" UNIQUE ("profileId", "season", "region"))`);
        await queryRunner.query(`CREATE TABLE "round_group" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "profileId" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "matchGroupId" integer)`);
        await queryRunner.query(`CREATE TABLE "match_group" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "profileId" varchar NOT NULL, "queue" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "player_comments" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "profileId" varchar NOT NULL, "name" varchar NOT NULL, "comment" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "ranks_snapshots" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "profileId" varchar NOT NULL, "season" integer NOT NULL, "apacSkillMean" integer NOT NULL, "apacSkillStdev" integer NOT NULL, "apacWins" integer NOT NULL, "apacLosses" integer NOT NULL, "apacAbandons" integer NOT NULL, "apacMmr" integer NOT NULL, "apacMaxMmr" integer NOT NULL, "apacRank" integer NOT NULL, "apacMaxRank" integer NOT NULL, "emeaSkillMean" integer NOT NULL, "emeaSkillStdev" integer NOT NULL, "emeaWins" integer NOT NULL, "emeaLosses" integer NOT NULL, "emeaAbandons" integer NOT NULL, "emeaMmr" integer NOT NULL, "emeaMaxMmr" integer NOT NULL, "emeaRank" integer NOT NULL, "emeaMaxRank" integer NOT NULL, "ncsaSkillMean" integer NOT NULL, "ncsaSkillStdev" integer NOT NULL, "ncsaWins" integer NOT NULL, "ncsaLosses" integer NOT NULL, "ncsaAbandons" integer NOT NULL, "ncsaMmr" integer NOT NULL, "ncsaMaxMmr" integer NOT NULL, "ncsaRank" integer NOT NULL, "ncsaMaxRank" integer NOT NULL, "isHandled" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "snapshot_tags" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "profileId" varchar NOT NULL, "name" varchar NOT NULL, "rankSnapshotId" integer NOT NULL, "statsSnapshotId" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_101379d8977731a9ad012cbb67e" UNIQUE ("profileId", "rankSnapshotId"))`);
        await queryRunner.query(`CREATE TABLE "stats_snapshots" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "profileId" varchar NOT NULL, "casualKills" integer NOT NULL, "casualDeaths" integer NOT NULL, "casualMatchLost" integer NOT NULL, "casualMatchPlayed" integer NOT NULL, "casualMatchWon" integer NOT NULL, "casualTimePlayed" integer NOT NULL, "generalBulletsFired" integer NOT NULL, "generalBulletsHit" integer NOT NULL, "generalHeadshot" integer NOT NULL, "generalDeaths" integer NOT NULL, "generalKillAssists" integer NOT NULL, "generalKills" integer NOT NULL, "generalMatchLost" integer NOT NULL, "generalMatchPlayed" integer NOT NULL, "generalMatchWon" integer NOT NULL, "generalMeleeKills" integer NOT NULL, "generalPenetrationKills" integer NOT NULL, "generalRevive" integer NOT NULL, "generalTimePlayed" integer NOT NULL, "generalBlindKills" integer NOT NULL, "generalDbno" integer NOT NULL, "generalDbnoAssists" integer NOT NULL, "generalGadgetDestroy" integer NOT NULL, "generalRappelBreach" integer NOT NULL, "generalReviveDenied" integer NOT NULL, "generalSuicide" integer NOT NULL, "rankedKills" integer NOT NULL, "rankedDeaths" integer NOT NULL, "rankedMatchLost" integer NOT NULL, "rankedMatchPlayed" integer NOT NULL, "rankedMatchWon" integer NOT NULL, "rankedTimePlayed" integer NOT NULL, "secureBestScore" integer NOT NULL, "secureMatchLost" integer NOT NULL, "secureMatchPlayed" integer NOT NULL, "secureMatchWon" integer NOT NULL, "secureAggression" integer NOT NULL, "secureDefense" integer NOT NULL, "secureHacked" integer NOT NULL, "hostageBestScore" integer NOT NULL, "hostageMatchLost" integer NOT NULL, "hostageMatchPlayed" integer NOT NULL, "hostageMatchWon" integer NOT NULL, "hostageDefense" integer NOT NULL, "hostageRescue" integer NOT NULL, "bombBestScore" integer NOT NULL, "bombMatchLost" integer NOT NULL, "bombMatchPlayed" integer NOT NULL, "bombMatchWon" integer NOT NULL, "operators" varchar NOT NULL, "isHandled" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "temporary_round_group" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "profileId" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "matchGroupId" integer, CONSTRAINT "FK_56536af5f369fce158930e21ac3" FOREIGN KEY ("matchGroupId") REFERENCES "match_group" ("id"))`);
        await queryRunner.query(`INSERT INTO "temporary_round_group"("id", "profileId", "createdAt", "matchGroupId") SELECT "id", "profileId", "createdAt", "matchGroupId" FROM "round_group"`);
        await queryRunner.query(`DROP TABLE "round_group"`);
        await queryRunner.query(`ALTER TABLE "temporary_round_group" RENAME TO "round_group"`);
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "round_group" RENAME TO "temporary_round_group"`);
        await queryRunner.query(`CREATE TABLE "round_group" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "profileId" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "matchGroupId" integer)`);
        await queryRunner.query(`INSERT INTO "round_group"("id", "profileId", "createdAt", "matchGroupId") SELECT "id", "profileId", "createdAt", "matchGroupId" FROM "temporary_round_group"`);
        await queryRunner.query(`DROP TABLE "temporary_round_group"`);
        await queryRunner.query(`DROP TABLE "stats_snapshots"`);
        await queryRunner.query(`DROP TABLE "snapshot_tags"`);
        await queryRunner.query(`DROP TABLE "ranks_snapshots"`);
        await queryRunner.query(`DROP TABLE "player_comments"`);
        await queryRunner.query(`DROP TABLE "match_group"`);
        await queryRunner.query(`DROP TABLE "round_group"`);
        await queryRunner.query(`DROP TABLE "current_ranks"`);
    }

}
